### PR TITLE
Fix KotlinNullPointerException

### LINKED ISSUE #149: Default pet not as specified in config.
The default pet I specified in the config does not work!

New players simply get a grass pet with no particle effects. Also it is not spawned by default (as it should according to my config)

Config:

```
join:
  enabled: true
  overwrite-previous-pet: false
  settings:
    petname: ":player's Tierchen"
    engine: 1
    id: 57
    damage: 0
    unbreakable: false
    skin: ''
    enabled: true
    age: 1
    effect:
      name: 'reddust'
      speed: 0.01
      amount: 20
      red: 0
      green: 0
      blue: 255
```

Versions:

- PetBlocks: 7.1.0-SNAPSHOT (btw it still says 7.0.1 ingame. Use `/sponge plugins petblocks` to see)
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-7d8a938
- SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
- Minecraft Forge: 14.23.3.2655

### LINKED ISSUE #150: KotlinNullPointerException when player with disabled pet joins
When a player joins and has their pet disabled, I get this exception:

```
> [18:23:25] [pool-3-thread-9/ERROR] [Sponge]: The Scheduler tried to run the task petblocks-A-336 owned by Plugin{id=petblocks, name=PetBlocks, version=7.0.1, description=PetBlocks is a spigot and sponge plugin to use blocks and custom heads as pets in Minecraft., authors=[Shynixn], source=/home/container/mods/1.12.2/PetBlocks-Sponge-7.1.0-20180512.090046-2.jar}, but an error occured.
com.github.shynixn.petblocks.lib.kotlin.KotlinNullPointerException: null
at com.github.shynixn.petblocks.sponge.logic.persistence.configuration.Config.fixJoinDefaultPet(Config.kt:86) ~[Config.class:?]
at com.github.shynixn.petblocks.sponge.logic.business.listener.SpongePetDataListener.lambda$playerJoinEvent$5(SpongePetDataListener.java:149) ~[SpongePetDataListener.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2655-7.1.0-BETA-3065]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2655-7.1.0-BETA-3065]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_161]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_161]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

Versions:

- PetBlocks: 7.1.0-SNAPSHOT
- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-7d8a938
- SpongeForge: 1.12.2-2655-7.1.0-BETA-3065
- Minecraft Forge: 14.23.3.2655

### PR DESCRIPTION
**Pull request by BrainStone**
when trying to get the default pet.

Fixes #149
Fixes #150

### CODE REVIEW

**Comment by BrainStone** [comment]
Looks like it still doesn't work...

I'll do some more fiddling around.

**Comment by BrainStone** [comment]
Nevermind, it works. I should have paid attention to version I was building...

**Comment by BrainStone** [comment]
If you want I'll recreate these changes for Bukkit too.

**Comment by Shynixn** [comment]
Thanks for your contribution :) Did you manage to setup a PetBlocks workspace (as it is a bit complicated) or just edited the Strings? 
I would appreciate it if you can also do it for Bukkit. I'll check this request now and publish a snapshot.

**Comment by BrainStone** [comment]
I manually edited the files, but I built it and am currently running this version on my server and it works flawlessly.

It may be worth trying to switch to gradle completely, as that would definitely lower the barrier of entry.

**Comment by Shynixn** [comment]
That's true but I have already tried to migrate to gradle and I had to add lots of maven compatibility fields in order to publish it into the maven central repository. It did not seem worth it and also the ForgeGradle plugin is terrible to integrate into a multi module project with dependencies. 

Also, I cannot change the way how the spigot and mcp libraries are managed because of the licensing issues, so gradle would not help to solve this.

**Pull request merged**
